apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: api-service-account-token
  namespace: graphql-mesh
  annotations:
    kubernetes.io/service-account.name: api-service-account